#!/bin/bash

echo -e "\033[35mLütfen kontrol etmek istediğiniz şifreyi girin:\033[0m "
read -sp "" password
echo

if [ ${#password} -lt 8 ]; then
    echo "Şifre zayıf: En az 8 karakter olmalı."
else
    echo "Şifre yeterli uzunlukta."
fi

case $password in
    [0-9])
        echo "Şifre rakam içeriyor: Güçlü."
        ;;
    *)
        echo "Şifre rakam içermiyor: Zayıf."
        ;;
esac

if [[ $password =~ [A-Z] ]]; then
    echo "Şifre büyük harf içeriyor: Güçlü."
else
    echo "Şifre büyük harf içermiyor: Zayıf."
fi

if [[ $password =~ [a-z] ]]; then
    echo "Şifre küçük harf içeriyor: Güçlü."
else
    echo "Şifre küçük harf içermiyor: Zayıf."
fi
